language: php
php:
  - "7.4"
  - "7.3"
  - "7.2"
env:
  - TESTBENCH_VERSION=^6.2
  - TESTBENCH_VERSION=^5.2
  - TESTBENCH_VERSION=^4.8
before_install:
  - composer require --dev "orchestra/testbench:${TESTBENCH_VERSION}"
install:
  - composer install -n
script:
  - composer test:dist
after_success:
  - travis_retry composer test:coverage
